### ISSUE TITLE
Not working on Obsidian Mobile (iPad)

### ISSUE THREAD

**Issue by knowledgepods** [michaellee/stille#1]
Thanks for a great experience on the desktop. This is fantastic. 

I have now moved to the iPad for almost all of my writing, and would love to have this plugin work with the mobile version. 

It installs fine but the stille 'toggle' does not do any toggle. Tested after disabling all themes and plugins.

**Comment by michaellee** [comment]
@knowledgepods thanks for the kind words and for checking my work out!

I definitely want to bring support to the iPad. I'm not sure how to do so yet, but once I figure it out, I'll be sure to let you know!

**Comment by dcalacci** [comment]
+1 for this from me! Happy to take a look in the new year, I may have some time and have been meaning to look into obsidian plugin structure.

**Comment by michaellee** [comment]
@dcalacci that would be amazing to get some assistance!

**Comment by dcalacci** [comment]
I'll drop a note here if/when I have time to peek at this

**Comment by michaellee** [comment]
@dcalacci I got some tips on how to add iOS and iPadOS compatibility from the forum https://forum.obsidian.md/t/adding-ios-and-ipados-compatibility-to-plugin/32305?u=michaellee

Unfortunately, I still wasn't able to figure out how to get it to work on mobile. I used the switch as suggested in the forum post. While it worked on desktop, trying it on my phone didn't lead to any different solutions. You can see my latest refactor in this commit https://github.com/michaellee/stille/commit/3c6164508ba1c290be9a067a121067c0474c7f71

**Comment by michaellee** [comment]
@knowledgepods @dcalacci check out version 1.1.0 of the iOS version of Obsidian. Along with at least version 1.0.3 of Stille, should get your Stille working on iOS. Let me know!

**Comment by knowledgepods** [comment]
Awesome! Working exactly as expected on my iPad. Thanks for getting this done.

**Comment by michaellee** [comment]
@knowledgepods excellent!

Happy writing :)
