### ISSUE TITLE
it dose not work in obsidian v0.13.31

### ISSUE THREAD

**Issue by ghost** [michaellee/stille#10]

**Comment by michaellee** [comment]
@Xieleilab could you tell me which version of Stille you have installed?

I just installed version 0.13.31 of Obsidian and there are no issues with Stille version 1.1.0.

**Comment by ghost** [comment]
v1.1.0, in obsidian v0.13.31,the theme is the default theme

**Comment by michaellee** [comment]
Hey @Xieleilab sorry it's been a while since I followed up. But are you still having issues with Stille and Obsidian?

I'm currently on v0.15.9 on macOS with Stille 1.2.0 and it works without issues.

By they way which OS are you using?

**Comment by ghost** [comment]
it now works tanks a lot

**Comment by michaellee** [comment]
Great, thanks for the confirmation @Xieleilab
