### ISSUE TITLE
Silence page file name

### ISSUE THREAD

**Issue by wowxunyl** [michaellee/stille#11]
Could you add a feature to silence page title name ?  I think this is a little unnatural. As follow:

<img width="722" alt="image" src="https://user-images.githubusercontent.com/8166109/174933002-678c1a65-bbb2-4f53-b915-7a59a905efc2.png">

**Comment by michaellee** [comment]
Thanks @wowxunyl for the suggestion! I'll see what I can do when I have a free cycle.

**Comment by michaellee** [comment]
Hey @wowxunyl I just released version 1.2.0

You should be able to update the plugin and then find the new toggle in the settings. Turning it on will then allow the title to dim.

Let me know if this helps and I can close this issue out.

**Comment by wowxunyl** [comment]
@michaellee I experienced it and that's what I want. Really excellent job and I appreciate it so much! But it seems that the option "Dim title" not always works. Here are the steps to reproduce:

1. Enable the "Dim title" option
2. Type "Toggle Still" command, title and content dim, as expected
3. Type "Toggle Still" command, title and content not dim, as expected
4. Type "Toggle Still" command, content dim, but title not dim, **NOT** expected

**Comment by michaellee** [comment]
@wowxunyl that's a good catch! I just pushed up v1.2.1 which should fix that issue.

Could you try it again after updating to the latest version?

**Comment by wowxunyl** [comment]
@michaellee I updated the latest version and it works smoothly. Love the perfect plugin! Thanks for your efforts so much!
