### ISSUE TITLE
Add option to silence reading view

### ISSUE THREAD

**Issue by wowxunyl** [michaellee/stille#12]
Currently, stille only affects writing view. When I switch to reading view, sitlle not affects. Is it possible to silence reading view also?  Thanks a lot.

**Comment by michaellee** [comment]
Let me look into this @wowxunyl

**Comment by michaellee** [comment]
I don't think this will be possible.

The reason being, in the editing mode, the cursor is used to indicate focus of a section of the document.

In reading mode this doesn't really exist so I won't be able to "track" where focus and unfocus is for Stille to work.
