### ISSUE TITLE
Not working at all on Obsidian v0.15.9

### ISSUE THREAD

**Issue by olliebaum** [michaellee/stille#15]
Hi, I have installed v1.2.1 on Obsidian v0.15.9 and unfortunately it is not working at all for me.
I have tried switching themes, restarting Obsidian, changing from light to dark mode etc.

**Comment by michaellee** [comment]
Hey @olliebaum thanks for reaching out. Is this the first time you're installing Stille?

**Comment by olliebaum** [comment]
Yes, this is the first time installing for me.

**Comment by michaellee** [comment]
Are you able to toggle using the icon on the left?

![Screen Shot 2022-09-07 at 1 16 09 PM](https://user-images.githubusercontent.com/1329644/188939773-82e3179d-a07b-449a-9fe6-85028e18a9bf.png)

Alternatively, you could use the command as well.

![Screen Shot 2022-09-07 at 1 16 34 PM](https://user-images.githubusercontent.com/1329644/188939782-79146108-aff1-4c62-ba79-fbe295c670ca.png)

Stille will only work in editing mode.

**Comment by olliebaum** [comment]
Ah, okay. This got it working for me. Thanks!
It would be good to add this to the Readme, otherwise it's not obvious these buttons/toggles exist.

**Comment by michaellee** [comment]
Awesome suggestion @olliebaum I'll be sure to do that. Thank you so much for bringing this to my attention!

**Comment by michaellee** [comment]
@olliebaum I've added a "Getting started" section to the repo's read me. Have a read https://github.com/michaellee/stille#getting-started and let me know if you think this is sufficient for other new users of Stille. Thanks!

**Comment by olliebaum** [comment]
Looks good. Cheers for that.

**Comment by michaellee** [comment]
Amazing! Thanks for the support and for bringing this to my attention :)
