### ISSUE TITLE
Follow input cursor aswell.

### ISSUE THREAD

**Issue by generic-user** [michaellee/stille#17]
Right now revealing of dimmed-sections follows the mouse pointer, would it be possible to follow the current active line as well, aka text cursor?
![example](https://user-images.githubusercontent.com/1516035/196404906-96e99311-1f30-46a5-8095-88c68cef3a22.png)

@michaellee Thanks for developing and sharing the application plugin, your work is appreciated! 🎉

**Comment by michaellee** [comment]
Hey @generic-user I hope you're doing well!

The behavior you've pointed out in your gif doesn't look like Stille. I think it's a different plugin. Stille's side ribbon icon is actually a crescent.

Stille doesn't actually do anything with the cursor's hover state. It actually does interact with the current active line as you pointed out.

If you haven't tried Stille, please do give it a shot, it might be what you're looking for https://obsidian.md/plugins?id=obsidian-stille

**Comment by generic-user** [comment]
You're absolutely right, I'm sorry for wasting your time. 

Stille is exactly what I need, thanks! 👍

**Comment by michaellee** [comment]
@generic-user awesome! Glad I was still able to help.

Not a waste of time at all, thanks for reaching out and have a great day!
