### ISSUE TITLE
Toggling off Stille makes status bar label appear

### ISSUE THREAD

**Issue by Scysta** [michaellee/stille#18]
Hi, I love your plugin! I found a bug where the status bar label is visible even if the option is turned off, but only when toggling off Stille. I'm running Obsidian 1.0.0 on Linux and installed the plugin today, if that's useful.

Edit: Using the ribbon in the left toolbar and the default shortcut also has this behaviour.

https://user-images.githubusercontent.com/76852113/197417104-3b9e0dac-920e-4ad4-ba73-9a5dcbb7010c.mp4

**Comment by michaellee** [comment]
Hey @Scysta thank you so much for the love of my work AND for bringing this gnarly bug to my attention.

I think I've squashed the issue now. Please update Stille to the latest version which is 1.3.2 and give it a shot.

You might have to also toggle the plugin off and on for it to take affect.

Please let me know if it works out!

**Comment by Scysta** [comment]
@michaellee It works perfectly now! 

Thank you for the quick response and I hope you have a great week!

**Comment by michaellee** [comment]
@Scysta awesome! Thanks for verifying!

Please have a great week as well :)
