### ISSUE TITLE
FR: Option to exclude current lowest heading level from being dimmed

### ISSUE THREAD

**Issue by ArtemisFowl-San** [michaellee/stille#19]
Hey there,
 I really love your plug in, because it reduces the visual noise in Obsidian, so thanks for creating it :) 
 
 
One thing I find myself wishing sometimes is the option to keep the current heading I am writing under from being dimmed as well, because I sometimes write short passages with different headings and then the header serves as a north star for keeping my writing concise and on topic. 

Would it be possible to give the option to have one header not be dimmed when using the plug in?

**Comment by michaellee** [comment]
Hey @ArtemisFowl-san any chance you could send me a screenshot of what you had in mind or at least provide some context?

I'm not sure, I fully understand what you're asking for 😄

**Comment by ArtemisFowl-San** [comment]
Hey @michaellee , thanks for the quick reply.


Here is an example of what I mean: the paragraphy below the heading is highlighted,  but the heading itself is not so I can lose the meta context of why I am writing something or what I am writing about, because it is harder to see. Obviously, I can still read the heading, but I would want to have them visually linked as a unit if that makes sense . 

![image](https://user-images.githubusercontent.com/72747914/214248391-050dc7a5-0074-4760-8f5f-3277661ab38c.png)

**Comment by michaellee** [comment]
Hey @ArtemisFowl-san thanks so much for the screenshot and explanation. I looked into this and it doesn't look like it's something Stille can support at this time. Obsidian provides a way to identify the current active element which is how Stille achieves the focus. But there's no way to track "adjacent" elements from the active element :(

**Comment by ArtemisFowl-San** [comment]
@michaellee  No worries, thanks for looking into this anyway. I still really enjoy the plug in :)
