### ISSUE TITLE
make stille available in community plugins

### ISSUE THREAD

**Issue by JasonAn** [michaellee/stille#2]
Stille is awesome! and why not make it available in community plugins, so more users can install and update it more smoothly?

**Comment by michaellee** [comment]
Hey @JasonAn thanks so much for the kind words! The plugin was just approved to be included in the community. You should be able to find it in Obsidian now. Let me know if you're able to see it as well 👍 

<img width="293" alt="Screen Shot 2021-09-13 at 9 50 33 AM" src="https://user-images.githubusercontent.com/1329644/133095763-e650ea11-28fc-424e-a31b-9a197ae38752.png">

**Comment by michaellee** [comment]
UNODIR, closing this issue out.
