### ISSUE TITLE
Feature: toggle sidebars/FS when activated

### ISSUE THREAD

**Issue by ke0pci** [michaellee/stille#20]
Stille has been a great addition to my academic writing. Thanks! 
As a new feature, please add "fullscreen" and "sidebars collapse"
With this feature, Stille goes into a true-focus mode, highlighting the current line of text and clearing obsidian's view as much as possible.  
Toggling Still mode off should return window sizing, left sidebar, and right sidebar to their original state. 
These two options would save three steps at the start and at the end of a heavy editing session:  (hide left sidebar, hide right sidebar, full-screen)

**Comment by michaellee** [comment]
Hey @ke0pci thanks for the suggestion! I like this idea, but I'm not sure if I'd bake this into Stille itself. I might write a separate plugin to handle just this. I like to create very minimal, single scoped plugins.

I'll let you know if I find some cycles to create such a plugin.

Thanks for using Stille and I'm glad it's helping you with your writing :)

**Comment by michaellee** [comment]
@ke0pci search for "Soomda" in the plugin directory. I released a plugin that does this https://github.com/michaellee/soomda
