### ISSUE TITLE
Support  obsidian properties

### ISSUE THREAD

**Issue by wowxunyl** [michaellee/stille#24]
Recently, Obsidian released the 'Properties' feature, but I found that stille doesn't work for it. I really appreciate your support for Obsidian properties.

**Comment by michaellee** [comment]
Thanks for letting me know and for using Stille all these years @wowxunyl

Let me look into it. I haven’t used properties myself.

**Comment by michaellee** [comment]
So I looked into this tonight, @wowxunyl and I can have the Properties box dim. But there doesn't seem to be a way to undim when the Properties box has focus.

So when moving your cursor on the screen, if it ever focused on the Properties UI, I won't be able to put it in focus.

If this sounds like an ok solution, happy to put in the support and push it out.

<img width="433" alt="Screenshot 2023-10-11 at 10 54 28 PM" src="https://github.com/michaellee/stille/assets/1329644/85455378-a3aa-4a67-ab05-33dc55c66742">

**Comment by wowxunyl** [comment]
@michaellee I think it is a acceptable solution as it ensures a consistent UI across all sections of the document. Thank you for your hard work and dedication!

**Comment by michaellee** [comment]
Just pushed out an update. Should show up in 1.3.4

Give it a try and then feel free to close this Issue out.

**Comment by wowxunyl** [comment]
I tried it out, and it turned out exactly as I expected. It's fantastic!
