### ISSUE TITLE
[Feature] Paragraph mode.

### ISSUE THREAD

**Issue by Karta775** [michaellee/stille#25]
Hi, i really like the extension but was hoping for the ability to make the current paragraph (text between two newlines, or between a heading and a newline) opaque instead of just the current line. Could it be implemented as a toggleable option in the settings?

Thanks :)

**Comment by michaellee** [comment]
Hey @Karta775 thanks for using Stille and reaching out.

I'm not quite sure I understand the desired outcome. Anything you can mock up or describe the use case, so I can understand better?

Thanks!

**Comment by Karta775** [comment]
Heading 1 has two lines of lorem ipsum. The normal behaviour is to highlight the selected line (i.e. only one of the lines of lorem ipsum in heading 1 would be highlighted), the behaviour in the mockup shows the entire paragraph (both lines plus the heading) highlighted.

<img width="873" alt="mockup" src="https://github.com/michaellee/stille/assets/83785288/6f699b45-b6cc-47ea-9437-a5e392031552">

**Comment by michaellee** [comment]
Hmmm I looked into this a little tonight and unfortunately I don't think I'd be able to implement this so easily. Stille uses CSS selectors to achieve most of its current functionality.

While CSS has the ability to select sibling elements, it lacks the ability to have fine-grained control over which siblings 🙁

**Comment by Karta775** [comment]
Oh I see, that's a shame. Thank you for looking into it :)
