### ISSUE TITLE
Desktop: When highlighting word/sentence Stille loses focus

### ISSUE THREAD

**Issue by michaellee** [michaellee/stille#3]
As described by @thepru on [Twitter](https://twitter.com/thepru/status/1436857908491395072?s=20), when highlighting words or a sentence, Stille will lose focus on desktop.

The reason this is happening is because Stille currently relies on the `.CodeMirror-activeline` selector to determine the focused section.

When the user highlights a word or sentence, Obsidian understandably "releases" this selector from the DOM, which is why Stille loses focus.

**Comment by lucaorio** [comment]
@michaellee Hello! 👋 Is this something that can be addressed or it's currently unsolvable?

**Comment by michaellee** [comment]
Hey @lucaorio at the time when I released Stille, I couldn't solve this. I believe since then they had updated the API for plugins. I will look into it soon and see if I can create a solution for it. Thanks for reaching out!

**Comment by michaellee** [comment]
@lucaorio seems the latest update 1.0.2 has fixed this issue. Give it a shot and let me know!

**Comment by lucaorio** [comment]
Hi @michaellee, thanks a lot for reminding me. Indeed, it all looks and works great now!
This ticket can definitely be closed :)

**Comment by michaellee** [comment]
Awesome, thanks @lucaorio for verifying. Closing this out 😄
