### ISSUE TITLE
Not working on Live preview mode

### ISSUE THREAD

**Issue by Miaoyifei-mz** [michaellee/stille#4]
As the problem shows, when switching to Live preview mode, stille don't work. （Obsidian version ：0.13.14）

**Comment by zhaozhiliao** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by onqun** [comment]
Not working at all in my computer :/

**Comment by basekno** [comment]
same issue   with obsidian0.13.19

**Comment by michaellee** [comment]
Hey @Miaoyifei-mz @zhaozhiliao @Akimaru666 @onqun @basekno this has been updated in the latest 1.0.2 version. You should be able to update it using the plugin update feature within Obsidian. Thanks for your patience!

**Comment by michaellee** [comment]
Closing this out as version 1.0.2 was confirmed as fixing issues for live preview.
