### ISSUE TITLE
Fade entire document when losing focus

### ISSUE THREAD

**Issue by wowxunyl** [michaellee/stille#6]
Now when I switch to other application, stille will not hide the document. Could you add one option to fade all when losing focus?

**Comment by michaellee** [comment]
Hey @wowxunyl! I'm not sure I completely understand what you're requesting. Could you elaborate a little bit more please on what the intended interaction is?

**Comment by wowxunyl** [comment]
Hey @michaellee! Currently, other sections are silenced when I am writing, which is expected. However , when I click other place(such as status bar) or switch to other application(such as chrome), all sections are not silenced . In other words , sections will not be silenced when cursor leaves the edit area.

I want to make all sections silenced when I leave the edit area . I will appreciate it if you can add an option to decide if the document silenced or not when the cursor is not on the edit area .

**Comment by michaellee** [comment]
@wowxunyl I've just released version 1.0.3 and it should fix the issue you shared above. Update the plugin and let me know if this helps. Thanks!

**Comment by wowxunyl** [comment]
@michaellee I updated the plugin and tried it, that's exactly what I want.  This helps me a lot and thank you so much!

**Comment by michaellee** [comment]
Awesome! Glad to hear it @wowxunyl! You're welcome :)
