### ISSUE TITLE
Not working on Mobile Android

### ISSUE THREAD

**Issue by JuergenKaettnis** [michaellee/stille#7]
I appreciate very much the purpose of the plugin and it is exactly what I am searching for. Unfortunately, Stille does something, but not what it is supposed to do. It just fades out the whole text, including the sentence the cursor is in.

**Comment by michaellee** [comment]
Hey @Hansilein00726 thanks for letting me know! I would bet that the same issues that are on iOS and iPadOS are the same for Android.

I don't actually know how to get it working correctly on mobile yet. But I've reached out in the forums to see if anyone can direct me to the right direction. Once I get some head way, I'll let you know.

In the mean time, sorry it doesn't work out of the box for you on Android.

**Comment by JuergenKaettnis** [comment]
Hi there! Just wanted to let you know that after release of the new Obsidian version your plugin works. The active line is highlighted. But wouldn't it be better to highlight the active sentence, i.e. the space between two ".", but there also other punctuation marks to be regarded. The app "ia writer" has implemented such a feature and works with markdown, too. Anyway, I can now use your plugin. Thank you very much for your great work.
