### ISSUE TITLE
Possible to Remove Notification from Status Bar?

### ISSUE THREAD

**Issue by ReaderGuy42** [michaellee/stille#8]
Would it be possible to have an option to disable to the entry int eh status bar that says whether or not Stille is on?

Thanks :)

**Comment by michaellee** [comment]
Hey @ReaderGuy42 thanks for the suggestion. So you want to be able to remove the status bar label that indicates whether Stille is on or off. Is that correct?

**Comment by ReaderGuy42** [comment]
Yes, exactly :) I just prefer to have as little as possible in the status bar, that's why I ask. Thanks!

**Comment by michaellee** [comment]
Ok, great! Now I understand @ReaderGuy42 thanks :)

Let me look into it.

**Comment by michaellee** [comment]
@ReaderGuy42 I've just release 1.1.0 which adds a new settings toggle to turn the status bar label on and off. Give it a shot and let me know if that works!

**Comment by ReaderGuy42** [comment]
Yes, perfect, thank you!!
