### ISSUE TITLE
Replace highlighting block by highlighting sentence

### ISSUE THREAD

**Issue by JuergenKaettnis** [michaellee/stille#9]
This is not really an issue, but I don't know where to put it: maybe it would be better to highlight the active sentence or the active line.

**Comment by michaellee** [comment]
Hey @Hansilein00726 thanks for sharing this concern. I saw your other message in #7 

Could you share a screenshot of what you're referring to? I want to make sure I fully understand the concern.

I believe you referenced IA Writer as well. Have any screenshots of this as well?

**Comment by wenbopeng** [comment]
> This is not really an issue, but I don't know where to put it: maybe it would be better to highlight the active sentence or the active line.

Maybe this plugin can help you: https://github.com/artisticat1/focus-active-sentence
